version: '3.8'

services:
  db:
    container_name: bookshopdbimage
    image: postgres:12.7
    restart: always
    environment:
      POSTGRES_DB: bookshopdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 7432:5432